### ISSUE TITLE
Temporary errors while connecting the sentinel

### ISSUE THREAD

**Issue by mle-enso** [idealo/logback-redis#15]
From time to time the appender looses connection to the sentinel, which leads to log messages like…
```
redis.clients.jedis.JedisSentinelPool
ERROR
Lost connection to Sentinel at node-01:26379. Sleeping 5000ms and retrying.
```
This happens not with all applications connected to Redis, further results will be added here as investigation continues.

**Comment by lkwg82** [comment]
I agree this is no ERROR, at least not while the buffer is not filled.

**Comment by lkwg82** [comment]
@cdanzl we should have a discussion if this an infrastructure problem or should not be logged as error

**Comment by vsdev1** [comment]
In my view this should not be logged as an error. It could be logged with level WARN if messages are lost, as INFO otherwise.

**Comment by lkwg82** [comment]
I agree, so we should discuss this upstream, when @cdanzl agrees as well

**Comment by lkwg82** [comment]
These non critical hickups were found to be an configuration issue. The redis-cluster should have enabled keepalive.
