### ISSUE TITLE
Adapt to API changes in logback-core >= 1.2.0

### ISSUE THREAD

**Issue by mle-enso** [idealo/logback-redis#16]
https://logback.qos.ch/news.html informs about an API change:

> Encoder interface has changed and is no longer expected to handle an OutputStream.

The logback-redis artifact relies on exactly this breaking change at the following place:

```de.idealo.logback.appender.RedisBatchAppender.createEncodedEvent(DeferredProcessingAware)```

So we need an upgrade at least for this method to stay upgradable to Logback >= 1.2.0 which is a mangaged dependency of https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-logging.

**Comment by lkwg82** [comment]
I will have a look into that tomorrow

**Comment by lkwg82** [comment]
The update of logback 1.2.x results into an major version change of this lib.

**Comment by lkwg82** [comment]
@mle-enso Is this issue still relevant?

**Comment by mle-enso** [comment]
Yes it is, for the same reason as stated in the initial description above.

Logback as a managed dependency of Spring Boot is upgraded to 1.2.x starting with Spring Boot >= 2.0 as can be seen here: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml

**Comment by doernbrackandre** [comment]
@mle-enso This project felt kind of asleep lately but we are working on this issue ATM so stay tuned

**Comment by mle-enso** [comment]
Woohooo! I appreciate your work!

**Comment by mle-enso** [comment]
Fixed with #18
