### ISSUE TITLE
Encoder version mismatch?

### ISSUE THREAD

**Issue by ask4gilles** [idealo/logback-redis#23]
Hi, 

I'm already using "net.logstash.logback:logstash-logback-encoder:4.11" in my app, which depends on 
logback-core 1.1.11.

I want to add your redis appender, but this method
`de.idealo.logback.appender.RedisBatchAppender#createEncodedEvent` relies on logback-core 1.2.3 : `encoder.encode` does not exist in logback-core 1.1.11

(I'm using spring boot 1.5.9 which provides also  logback-core 1.1.11 )

How can we fix this?
Thanks!

**Comment by ask4gilles** [comment]
I picked an older version of your lib (0.9.3) still compatible with logback-core.

**Comment by mgerlach** [comment]
Hi Gilles,

Another possibility would be to manage logback to 1.2.3 in your pom.xml. It's no problem for Spring Boot 1.5.x. If you inherit from the spring-boot-starter-parent, just set POM property logback.version to 1.2.3. If you rather import spring-boot-dependencies via dependencyManagement, you will need to explicitly add dependencies for logback-core, -classic, -access, etc. with version 1.2.3

**Comment by ask4gilles** [comment]
Thanks for your answer.
