### ISSUE TITLE
Add the possibility to publish to redis in addition to rpush

### ISSUE THREAD

**Issue by ask4gilles** [idealo/logback-redis#24]
It would be nice to have the possibility to publish in redis in addition to rpush:
Something like: `pipeline.publish(connectionConfig.getKey(), createEncodedEvent(event));`

**Comment by mgerlach** [comment]
Hi Gilles, 
thanks for the suggestion, we will look into this.
Cheers,
Martin

**Comment by ask4gilles** [comment]
Yep, cool 🙂

**Comment by mgerlach** [comment]
@ask4gilles feel free to review https://github.com/idealo/logback-redis/pull/31

**Comment by schabe77** [comment]
with version 1.4.0 you are able to PUBLISH to redis if you add 
``<method>PUBLISH</method>``
to connectionConfig
