### ISSUE TITLE
logstash-logback-encoder version

### ISSUE THREAD

**Issue by tillmannheigel** [idealo/logback-redis#25]
You write in the documentation: 

used best in conjuction with

```xml
<dependency>
   <groupId>net.logstash.logback</groupId>
   <artifactId>logstash-logback-encoder</artifactId>
   <version>4.11</version>
</dependency>      
```

Is there a strong need to use 4.11 or could it also be the latest version?

(which is at the moment)

```xml
 <version>5.1</version>
```

**Comment by mgerlach** [comment]
Hi,

it can also be 5.0 or 5.1

Cheers
Martin


Tillmann Heigel <notifications@github.com> schrieb am Mo., 4. Juni 2018,
14:50:

**Comment by tillmannheigel** [comment]
Hi Martin,

then I would think it makes sense to remove the version completely.

Best,
Tillmann
