### ISSUE TITLE
Documentation for SSL configuration

### ISSUE THREAD

**Issue by malcolmrobbins** [idealo/logback-redis#26]
Hi,
I'm trying to use this appender with SSL but it's not at all obvious to me how to configure the redis appender for SSL, presumably because the doco lags the code capability, but even when I debug the code it's not clear how it gets its SSL configuration. Can someone provide a few pointers and update the online doco as well?

**Comment by mgerlach** [comment]
Hi Malcolm, the author of the original pull request, @hieudbui, wrote in the respective thread that RedisConnectionConfig.ssl needs to be set to true. This can be achieved in logback.xml:
`<appender name="REDIS" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="de.idealo.logback.appender.RedisBatchAppender">
            <connectionConfig>
                <scheme>SENTINEL</scheme>
                <sentinelMasterName>${sentinel.master.name}</sentinelMasterName>
                <sentinels>${sentinel.host.list}</sentinels>
                <key>${sentinel.key}</key>
                <ssl>true</ssl>    
            </connectionConfig>
`
Have you tired that?

**Comment by malcolmrobbins** [comment]
Thanks for this.  I added this but then I get the exception below that suggests that there is something else not configured.  I'm sure there is soemthing basic I'm missing (to expand on the SSL config because when I look through the code I can see the JedisPool constructor can take SSLSocketFactory, SSLParameters and HostnameVerifier but I'm amiss to how those things can be populated.

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@30:22 - no applicable action for [ssl], current ElementPath  is [[configuration][appender][appender][connectionConfig][ssl]]
...etc

**Comment by mgerlach** [comment]
Thanks for providing the problem details. This looks like it's not going to work like @hieudbui and I suggested. We'll have to look into that. I hope my colleagues or myself will find some time soon. Until then, should you investigate further it would be great if you could share results here.

**Comment by mgerlach** [comment]
Hi Malcom,
thanks for sharing the problem details. I just realized that the SSL support has not been released yet :/ Sorry about that. I will try to create a release. You may also just build a version from master for yourself in the meantime.

**Comment by mgerlach** [comment]
Just built the release 1.1.0, that will support the <ssl> element in <connectionConfig>. It will take a while to appear on Maven Central, though.

**Comment by malcolmrobbins** [comment]
Thanks; that fixed things up nicely.

**Comment by mgerlach** [comment]
Well... leavi
